//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://fina.hr/eracun/b2b/ws/pki/v0.1", ConfigurationName="ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType")]
    public interface eRacunB2BPortType {
        
        // CODEGEN: Generating message contract since the operation echo is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/Echo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse echo(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/Echo", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse> echoAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest request);
        
        // CODEGEN: Generating message contract since the operation sendB2BOutgoingInvoice is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/SendB2BOutgoingInvoice", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse sendB2BOutgoingInvoice(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/SendB2BOutgoingInvoice", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse> sendB2BOutgoingInvoiceAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest request);
        
        // CODEGEN: Generating message contract since the operation sendB2BOutgoingInvoiceReporting is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/SendB2BOutgoingInvoiceReporting", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse sendB2BOutgoingInvoiceReporting(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/SendB2BOutgoingInvoiceReporting", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse> sendB2BOutgoingInvoiceReportingAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest request);
        
        // CODEGEN: Generating message contract since the operation getB2BOutgoingInvoiceStatus is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/GetB2BOutgoingInvoiceStatus", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse getB2BOutgoingInvoiceStatus(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://fina.hr/eracun/b2b/GetB2BOutgoingInvoiceStatus", ReplyAction="*")]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse> getB2BOutgoingInvoiceStatusAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
    public partial class EchoMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderSupplierType headerSupplierField;
        
        private EchoMsgData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public HeaderSupplierType HeaderSupplier {
            get {
                return this.headerSupplierField;
            }
            set {
                this.headerSupplierField = value;
                this.RaisePropertyChanged("HeaderSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EchoMsgData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
    public partial class HeaderSupplierType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string supplierIDField;
        
        private string additionalSupplierIDField;
        
        private string eRPIDField;
        
        private string messageTypeField;
        
        private string messageAttributesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
                this.RaisePropertyChanged("SupplierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string AdditionalSupplierID {
            get {
                return this.additionalSupplierIDField;
            }
            set {
                this.additionalSupplierIDField = value;
                this.RaisePropertyChanged("AdditionalSupplierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ERPID {
            get {
                return this.eRPIDField;
            }
            set {
                this.eRPIDField = value;
                this.RaisePropertyChanged("ERPID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=4)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string MessageAttributes {
            get {
                return this.messageAttributesField;
            }
            set {
                this.messageAttributesField = value;
                this.RaisePropertyChanged("MessageAttributes");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
    public partial class DocumentStatusType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private DocumentStatusTypeStatusCode statusCodeField;
        
        private string statusTextField;
        
        private System.DateTime statusTimestampField;
        
        private bool statusTimestampFieldSpecified;
        
        private string noteField;
        
        private decimal partialAmountField;
        
        private bool partialAmountFieldSpecified;
        
        private string documentCurrencyCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public DocumentStatusTypeStatusCode StatusCode {
            get {
                return this.statusCodeField;
            }
            set {
                this.statusCodeField = value;
                this.RaisePropertyChanged("StatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string StatusText {
            get {
                return this.statusTextField;
            }
            set {
                this.statusTextField = value;
                this.RaisePropertyChanged("StatusText");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime StatusTimestamp {
            get {
                return this.statusTimestampField;
            }
            set {
                this.statusTimestampField = value;
                this.RaisePropertyChanged("StatusTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StatusTimestampSpecified {
            get {
                return this.statusTimestampFieldSpecified;
            }
            set {
                this.statusTimestampFieldSpecified = value;
                this.RaisePropertyChanged("StatusTimestampSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string Note {
            get {
                return this.noteField;
            }
            set {
                this.noteField = value;
                this.RaisePropertyChanged("Note");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public decimal PartialAmount {
            get {
                return this.partialAmountField;
            }
            set {
                this.partialAmountField = value;
                this.RaisePropertyChanged("PartialAmount");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PartialAmountSpecified {
            get {
                return this.partialAmountFieldSpecified;
            }
            set {
                this.partialAmountFieldSpecified = value;
                this.RaisePropertyChanged("PartialAmountSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string DocumentCurrencyCode {
            get {
                return this.documentCurrencyCodeField;
            }
            set {
                this.documentCurrencyCodeField = value;
                this.RaisePropertyChanged("DocumentCurrencyCode");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
    public enum DocumentStatusTypeStatusCode {
        
        /// <remarks/>
        RECEIVED,
        
        /// <remarks/>
        PAYMENT_RECEIVED,
        
        /// <remarks/>
        RECEIVING_CONFIRMED,
        
        /// <remarks/>
        APPROVED,
        
        /// <remarks/>
        REJECTED,
        
        /// <remarks/>
        PAYMENT_FULFILLED,
        
        /// <remarks/>
        PAYMENT_PARTIALLY_FULFILLED,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
    public partial class MessageAckType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageIDField;
        
        private string messageAckIDField;
        
        private string messageTypeField;
        
        private AckStatusType ackStatusField;
        
        private int ackStatusCodeField;
        
        private string ackStatusTextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string MessageID {
            get {
                return this.messageIDField;
            }
            set {
                this.messageIDField = value;
                this.RaisePropertyChanged("MessageID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MessageAckID {
            get {
                return this.messageAckIDField;
            }
            set {
                this.messageAckIDField = value;
                this.RaisePropertyChanged("MessageAckID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string MessageType {
            get {
                return this.messageTypeField;
            }
            set {
                this.messageTypeField = value;
                this.RaisePropertyChanged("MessageType");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public AckStatusType AckStatus {
            get {
                return this.ackStatusField;
            }
            set {
                this.ackStatusField = value;
                this.RaisePropertyChanged("AckStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int AckStatusCode {
            get {
                return this.ackStatusCodeField;
            }
            set {
                this.ackStatusCodeField = value;
                this.RaisePropertyChanged("AckStatusCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string AckStatusText {
            get {
                return this.ackStatusTextField;
            }
            set {
                this.ackStatusTextField = value;
                this.RaisePropertyChanged("AckStatusText");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1")]
    public enum AckStatusType {
        
        /// <remarks/>
        ACCEPTED,
        
        /// <remarks/>
        MSG_NOT_VALID,
        
        /// <remarks/>
        SYSTEM_ERROR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
    public partial class EchoMsgData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private EchoMsgDataEchoData echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public EchoMsgDataEchoData EchoData {
            get {
                return this.echoDataField;
            }
            set {
                this.echoDataField = value;
                this.RaisePropertyChanged("EchoData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
    public partial class EchoMsgDataEchoData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string echoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Echo {
            get {
                return this.echoField;
            }
            set {
                this.echoField = value;
                this.RaisePropertyChanged("Echo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
    public partial class EchoAckMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageAckType messageAckField;
        
        private EchoAckMsgEchoData echoDataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public MessageAckType MessageAck {
            get {
                return this.messageAckField;
            }
            set {
                this.messageAckField = value;
                this.RaisePropertyChanged("MessageAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public EchoAckMsgEchoData EchoData {
            get {
                return this.echoDataField;
            }
            set {
                this.echoDataField = value;
                this.RaisePropertyChanged("EchoData");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1")]
    public partial class EchoAckMsgEchoData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string echoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Echo {
            get {
                return this.echoField;
            }
            set {
                this.echoField = value;
                this.RaisePropertyChanged("Echo");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoMsg EchoMsg;
        
        public echoRequest() {
        }
        
        public echoRequest(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoMsg EchoMsg) {
            this.EchoMsg = EchoMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class echoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/Echo/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoAckMsg EchoAckMsg;
        
        public echoResponse() {
        }
        
        public echoResponse(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoAckMsg EchoAckMsg) {
            this.EchoAckMsg = EchoAckMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderSupplierType headerSupplierField;
        
        private SendB2BOutgoingInvoiceMsgData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public HeaderSupplierType HeaderSupplier {
            get {
                return this.headerSupplierField;
            }
            set {
                this.headerSupplierField = value;
                this.RaisePropertyChanged("HeaderSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceMsgData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceMsgData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope {
            get {
                return this.b2BOutgoingInvoiceEnvelopeField;
            }
            set {
                this.b2BOutgoingInvoiceEnvelopeField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceEnvelope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard xMLStandardField;
        
        private SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier specificationIdentifierField;
        
        private string supplierInvoiceIDField;
        
        private string buyerIDField;
        
        private string additionalBuyerIDField;
        
        private byte[] itemField;
        
        private ItemChoiceType itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard XMLStandard {
            get {
                return this.xMLStandardField;
            }
            set {
                this.xMLStandardField = value;
                this.RaisePropertyChanged("XMLStandard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier SpecificationIdentifier {
            get {
                return this.specificationIdentifierField;
            }
            set {
                this.specificationIdentifierField = value;
                this.RaisePropertyChanged("SpecificationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuyerID {
            get {
                return this.buyerIDField;
            }
            set {
                this.buyerIDField = value;
                this.RaisePropertyChanged("BuyerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AdditionalBuyerID {
            get {
                return this.additionalBuyerIDField;
            }
            set {
                this.additionalBuyerIDField = value;
                this.RaisePropertyChanged("AdditionalBuyerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditNoteEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public byte[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public enum SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard {
        
        /// <remarks/>
        UBL,
        
        /// <remarks/>
        CII,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public enum SendB2BOutgoingInvoiceMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017")]
        urnceneuen169312017,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0")]
        urnceneuen169312017complianturnfdcpeppoleu2017poaccbilling30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:mfin.gov.hr:cius-2025:1.0#conformant#urn:mf" +
            "in.gov.hr:ext-2025:1.0")]
        urnceneuen169312017complianturnmfingovhrcius202510conformanturnmfingovhrext202510,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", IncludeInSchema=false)]
    public enum ItemChoiceType {
        
        /// <remarks/>
        CreditNoteEnvelope,
        
        /// <remarks/>
        InvoiceEnvelope,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceAckMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageAckType messageAckField;
        
        private SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public MessageAckType MessageAck {
            get {
                return this.messageAckField;
            }
            set {
                this.messageAckField = value;
                this.RaisePropertyChanged("MessageAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope {
            get {
                return this.b2BOutgoingInvoiceEnvelopeField;
            }
            set {
                this.b2BOutgoingInvoiceEnvelopeField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceEnvelope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing b2BOutgoingInvoiceProcessingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing B2BOutgoingInvoiceProcessing {
            get {
                return this.b2BOutgoingInvoiceProcessingField;
            }
            set {
                this.b2BOutgoingInvoiceProcessingField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceProcessing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IncorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierInvoiceIDField;
        
        private string invoiceIDField;
        
        private System.DateTime invoiceTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
                this.RaisePropertyChanged("InvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime InvoiceTimestamp {
            get {
                return this.invoiceTimestampField;
            }
            set {
                this.invoiceTimestampField = value;
                this.RaisePropertyChanged("InvoiceTimestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1")]
    public partial class SendB2BOutgoingInvoiceAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierInvoiceIDField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendB2BOutgoingInvoiceRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg;
        
        public sendB2BOutgoingInvoiceRequest() {
        }
        
        public sendB2BOutgoingInvoiceRequest(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg) {
            this.SendB2BOutgoingInvoiceMsg = SendB2BOutgoingInvoiceMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendB2BOutgoingInvoiceResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoice/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceAckMsg SendB2BOutgoingInvoiceAckMsg;
        
        public sendB2BOutgoingInvoiceResponse() {
        }
        
        public sendB2BOutgoingInvoiceResponse(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceAckMsg SendB2BOutgoingInvoiceAckMsg) {
            this.SendB2BOutgoingInvoiceAckMsg = SendB2BOutgoingInvoiceAckMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderSupplierType headerSupplierField;
        
        private SendB2BOutgoingInvoiceReportingMsgData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public HeaderSupplierType HeaderSupplier {
            get {
                return this.headerSupplierField;
            }
            set {
                this.headerSupplierField = value;
                this.RaisePropertyChanged("HeaderSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceReportingMsgData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingMsgData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope {
            get {
                return this.b2BOutgoingInvoiceEnvelopeField;
            }
            set {
                this.b2BOutgoingInvoiceEnvelopeField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceEnvelope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard xMLStandardField;
        
        private SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier specificationIdentifierField;
        
        private string supplierInvoiceIDField;
        
        private string buyerIDField;
        
        private string additionalBuyerIDField;
        
        private byte[] itemField;
        
        private ItemChoiceType1 itemElementNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard XMLStandard {
            get {
                return this.xMLStandardField;
            }
            set {
                this.xMLStandardField = value;
                this.RaisePropertyChanged("XMLStandard");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier SpecificationIdentifier {
            get {
                return this.specificationIdentifierField;
            }
            set {
                this.specificationIdentifierField = value;
                this.RaisePropertyChanged("SpecificationIdentifier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string BuyerID {
            get {
                return this.buyerIDField;
            }
            set {
                this.buyerIDField = value;
                this.RaisePropertyChanged("BuyerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string AdditionalBuyerID {
            get {
                return this.additionalBuyerIDField;
            }
            set {
                this.additionalBuyerIDField = value;
                this.RaisePropertyChanged("AdditionalBuyerID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CreditNoteEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute("InvoiceEnvelope", typeof(byte[]), DataType="base64Binary", Order=5)]
        [System.Xml.Serialization.XmlChoiceIdentifierAttribute("ItemElementName")]
        public byte[] Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public ItemChoiceType1 ItemElementName {
            get {
                return this.itemElementNameField;
            }
            set {
                this.itemElementNameField = value;
                this.RaisePropertyChanged("ItemElementName");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public enum SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeXMLStandard {
        
        /// <remarks/>
        UBL,
        
        /// <remarks/>
        CII,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public enum SendB2BOutgoingInvoiceReportingMsgDataB2BOutgoingInvoiceEnvelopeSpecificationIdentifier {
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017")]
        urnceneuen169312017,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:fdc:peppol.eu:2017:poacc:billing:3.0")]
        urnceneuen169312017complianturnfdcpeppoleu2017poaccbilling30,
        
        /// <remarks/>
        [System.Xml.Serialization.XmlEnumAttribute("urn:cen.eu:en16931:2017#compliant#urn:mfin.gov.hr:cius-2025:1.0#conformant#urn:mf" +
            "in.gov.hr:ext-2025:1.0")]
        urnceneuen169312017complianturnmfingovhrcius202510conformanturnmfingovhrext202510,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", IncludeInSchema=false)]
    public enum ItemChoiceType1 {
        
        /// <remarks/>
        CreditNoteEnvelope,
        
        /// <remarks/>
        InvoiceEnvelope,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingAckMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageAckType messageAckField;
        
        private SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope b2BOutgoingInvoiceEnvelopeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public MessageAckType MessageAck {
            get {
                return this.messageAckField;
            }
            set {
                this.messageAckField = value;
                this.RaisePropertyChanged("MessageAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope B2BOutgoingInvoiceEnvelope {
            get {
                return this.b2BOutgoingInvoiceEnvelopeField;
            }
            set {
                this.b2BOutgoingInvoiceEnvelopeField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceEnvelope");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelope : object, System.ComponentModel.INotifyPropertyChanged {
        
        private SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing b2BOutgoingInvoiceProcessingField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing B2BOutgoingInvoiceProcessing {
            get {
                return this.b2BOutgoingInvoiceProcessingField;
            }
            set {
                this.b2BOutgoingInvoiceProcessingField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceProcessing");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessing : object, System.ComponentModel.INotifyPropertyChanged {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("CorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("IncorrectB2BOutgoingInvoice", typeof(SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice), Order=0)]
        public object Item {
            get {
                return this.itemField;
            }
            set {
                this.itemField = value;
                this.RaisePropertyChanged("Item");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingCorrectB2BOutgoingInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierInvoiceIDField;
        
        private string invoiceIDField;
        
        private System.DateTime invoiceTimestampField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
                this.RaisePropertyChanged("InvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.DateTime InvoiceTimestamp {
            get {
                return this.invoiceTimestampField;
            }
            set {
                this.invoiceTimestampField = value;
                this.RaisePropertyChanged("InvoiceTimestamp");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1")]
    public partial class SendB2BOutgoingInvoiceReportingAckMsgB2BOutgoingInvoiceEnvelopeB2BOutgoingInvoiceProcessingIncorrectB2BOutgoingInvoice : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierInvoiceIDField;
        
        private string errorCodeField;
        
        private string errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendB2BOutgoingInvoiceReportingRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg;
        
        public sendB2BOutgoingInvoiceReportingRequest() {
        }
        
        public sendB2BOutgoingInvoiceReportingRequest(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg) {
            this.SendB2BOutgoingInvoiceReportingMsg = SendB2BOutgoingInvoiceReportingMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class sendB2BOutgoingInvoiceReportingResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/SendB2BOutgoingInvoiceReporting/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingAckMsg SendB2BOutgoingInvoiceReportingAckMsg;
        
        public sendB2BOutgoingInvoiceReportingResponse() {
        }
        
        public sendB2BOutgoingInvoiceReportingResponse(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingAckMsg SendB2BOutgoingInvoiceReportingAckMsg) {
            this.SendB2BOutgoingInvoiceReportingAckMsg = SendB2BOutgoingInvoiceReportingAckMsg;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
    public partial class GetB2BOutgoingInvoiceStatusMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private HeaderSupplierType headerSupplierField;
        
        private GetB2BOutgoingInvoiceStatusMsgData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public HeaderSupplierType HeaderSupplier {
            get {
                return this.headerSupplierField;
            }
            set {
                this.headerSupplierField = value;
                this.RaisePropertyChanged("HeaderSupplier");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetB2BOutgoingInvoiceStatusMsgData Data {
            get {
                return this.dataField;
            }
            set {
                this.dataField = value;
                this.RaisePropertyChanged("Data");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
    public partial class GetB2BOutgoingInvoiceStatusMsgData : object, System.ComponentModel.INotifyPropertyChanged {
        
        private GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus b2BOutgoingInvoiceStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus B2BOutgoingInvoiceStatus {
            get {
                return this.b2BOutgoingInvoiceStatusField;
            }
            set {
                this.b2BOutgoingInvoiceStatusField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
    public partial class GetB2BOutgoingInvoiceStatusMsgDataB2BOutgoingInvoiceStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierInvoiceIDField;
        
        private string invoiceYearField;
        
        private bool documentCurrencyCodeField;
        
        private bool documentCurrencyCodeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=1)]
        public string InvoiceYear {
            get {
                return this.invoiceYearField;
            }
            set {
                this.invoiceYearField = value;
                this.RaisePropertyChanged("InvoiceYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool DocumentCurrencyCode {
            get {
                return this.documentCurrencyCodeField;
            }
            set {
                this.documentCurrencyCodeField = value;
                this.RaisePropertyChanged("DocumentCurrencyCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocumentCurrencyCodeSpecified {
            get {
                return this.documentCurrencyCodeFieldSpecified;
            }
            set {
                this.documentCurrencyCodeFieldSpecified = value;
                this.RaisePropertyChanged("DocumentCurrencyCodeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
    public partial class GetB2BOutgoingInvoiceStatusAckMsg : object, System.ComponentModel.INotifyPropertyChanged {
        
        private MessageAckType messageAckField;
        
        private GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus b2BOutgoingInvoiceStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=0)]
        public MessageAckType MessageAck {
            get {
                return this.messageAckField;
            }
            set {
                this.messageAckField = value;
                this.RaisePropertyChanged("MessageAck");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus B2BOutgoingInvoiceStatus {
            get {
                return this.b2BOutgoingInvoiceStatusField;
            }
            set {
                this.b2BOutgoingInvoiceStatusField = value;
                this.RaisePropertyChanged("B2BOutgoingInvoiceStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9221.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1")]
    public partial class GetB2BOutgoingInvoiceStatusAckMsgB2BOutgoingInvoiceStatus : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string supplierIDField;
        
        private string additionalSupplierIDField;
        
        private string invoiceIDField;
        
        private string supplierInvoiceIDField;
        
        private System.DateTime invoiceTimestampField;
        
        private DocumentStatusType[] documentStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SupplierID {
            get {
                return this.supplierIDField;
            }
            set {
                this.supplierIDField = value;
                this.RaisePropertyChanged("SupplierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AdditionalSupplierID {
            get {
                return this.additionalSupplierIDField;
            }
            set {
                this.additionalSupplierIDField = value;
                this.RaisePropertyChanged("AdditionalSupplierID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=2)]
        public string InvoiceID {
            get {
                return this.invoiceIDField;
            }
            set {
                this.invoiceIDField = value;
                this.RaisePropertyChanged("InvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string SupplierInvoiceID {
            get {
                return this.supplierInvoiceIDField;
            }
            set {
                this.supplierInvoiceIDField = value;
                this.RaisePropertyChanged("SupplierInvoiceID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public System.DateTime InvoiceTimestamp {
            get {
                return this.invoiceTimestampField;
            }
            set {
                this.invoiceTimestampField = value;
                this.RaisePropertyChanged("InvoiceTimestamp");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("DocumentStatus", Namespace="http://fina.hr/eracun/b2b/invoicewebservicecomponents/v0.1", Order=5)]
        public DocumentStatusType[] DocumentStatus {
            get {
                return this.documentStatusField;
            }
            set {
                this.documentStatusField = value;
                this.RaisePropertyChanged("DocumentStatus");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getB2BOutgoingInvoiceStatusRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg;
        
        public getB2BOutgoingInvoiceStatusRequest() {
        }
        
        public getB2BOutgoingInvoiceStatusRequest(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg) {
            this.GetB2BOutgoingInvoiceStatusMsg = GetB2BOutgoingInvoiceStatusMsg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getB2BOutgoingInvoiceStatusResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://fina.hr/eracun/b2b/pki/GetB2BOutgoingInvoiceStatus/v0.1", Order=0)]
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusAckMsg GetB2BOutgoingInvoiceStatusAckMsg;
        
        public getB2BOutgoingInvoiceStatusResponse() {
        }
        
        public getB2BOutgoingInvoiceStatusResponse(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusAckMsg GetB2BOutgoingInvoiceStatusAckMsg) {
            this.GetB2BOutgoingInvoiceStatusAckMsg = GetB2BOutgoingInvoiceStatusAckMsg;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface eRacunB2BPortTypeChannel : WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class eRacunB2BPortTypeClient : System.ServiceModel.ClientBase<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType>, WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType {
        
        public eRacunB2BPortTypeClient() {
        }
        
        public eRacunB2BPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public eRacunB2BPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eRacunB2BPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public eRacunB2BPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.echo(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest request) {
            return base.Channel.echo(request);
        }
        
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoAckMsg echo(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoMsg EchoMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest();
            inValue.EchoMsg = EchoMsg;
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse retVal = ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).echo(inValue);
            return retVal.EchoAckMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse> WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.echoAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest request) {
            return base.Channel.echoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoResponse> echoAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.EchoMsg EchoMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.echoRequest();
            inValue.EchoMsg = EchoMsg;
            return ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).echoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.sendB2BOutgoingInvoice(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest request) {
            return base.Channel.sendB2BOutgoingInvoice(request);
        }
        
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceAckMsg sendB2BOutgoingInvoice(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest();
            inValue.SendB2BOutgoingInvoiceMsg = SendB2BOutgoingInvoiceMsg;
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse retVal = ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).sendB2BOutgoingInvoice(inValue);
            return retVal.SendB2BOutgoingInvoiceAckMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse> WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.sendB2BOutgoingInvoiceAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest request) {
            return base.Channel.sendB2BOutgoingInvoiceAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceResponse> sendB2BOutgoingInvoiceAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceMsg SendB2BOutgoingInvoiceMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceRequest();
            inValue.SendB2BOutgoingInvoiceMsg = SendB2BOutgoingInvoiceMsg;
            return ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).sendB2BOutgoingInvoiceAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.sendB2BOutgoingInvoiceReporting(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest request) {
            return base.Channel.sendB2BOutgoingInvoiceReporting(request);
        }
        
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingAckMsg sendB2BOutgoingInvoiceReporting(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest();
            inValue.SendB2BOutgoingInvoiceReportingMsg = SendB2BOutgoingInvoiceReportingMsg;
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse retVal = ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).sendB2BOutgoingInvoiceReporting(inValue);
            return retVal.SendB2BOutgoingInvoiceReportingAckMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse> WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.sendB2BOutgoingInvoiceReportingAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest request) {
            return base.Channel.sendB2BOutgoingInvoiceReportingAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingResponse> sendB2BOutgoingInvoiceReportingAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.SendB2BOutgoingInvoiceReportingMsg SendB2BOutgoingInvoiceReportingMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.sendB2BOutgoingInvoiceReportingRequest();
            inValue.SendB2BOutgoingInvoiceReportingMsg = SendB2BOutgoingInvoiceReportingMsg;
            return ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).sendB2BOutgoingInvoiceReportingAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.getB2BOutgoingInvoiceStatus(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest request) {
            return base.Channel.getB2BOutgoingInvoiceStatus(request);
        }
        
        public WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusAckMsg getB2BOutgoingInvoiceStatus(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest();
            inValue.GetB2BOutgoingInvoiceStatusMsg = GetB2BOutgoingInvoiceStatusMsg;
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse retVal = ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).getB2BOutgoingInvoiceStatus(inValue);
            return retVal.GetB2BOutgoingInvoiceStatusAckMsg;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse> WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType.getB2BOutgoingInvoiceStatusAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest request) {
            return base.Channel.getB2BOutgoingInvoiceStatusAsync(request);
        }
        
        public System.Threading.Tasks.Task<WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusResponse> getB2BOutgoingInvoiceStatusAsync(WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.GetB2BOutgoingInvoiceStatusMsg GetB2BOutgoingInvoiceStatusMsg) {
            WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest inValue = new WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.getB2BOutgoingInvoiceStatusRequest();
            inValue.GetB2BOutgoingInvoiceStatusMsg = GetB2BOutgoingInvoiceStatusMsg;
            return ((WpfCSCS.ServiceReference1_SendB2BOutgoingInvoicePKIWebService.eRacunB2BPortType)(this)).getB2BOutgoingInvoiceStatusAsync(inValue);
        }
    }
}
